const arabicPrefixesMap = new Map([
  ["أبو", "Abo"],
  ["د.", "Dr."],
  ["الاستاذ", "Mr."],
  ["الاستاذة", "Ms."],
  ["الاستاذة", "Ms."],
  ["ابو", "Abo"],
  ["أبا", "Aba"],
  ["ابا", "Aba"],
  ["أم", "Om"],
  ["ام", "Om"],
  ["أبوي", "Aboe"],
  ["ابوي", "Aboe"],
  ["أبن", "Ibn"],
  ["ابن", "Ibn"],
  ["أولاد", "Aolad"],
  ["اولاد", "Aolad"],
  ["بن", "Bn"],
  ["ابناء", "Abnaa"],
  ["السيد", "Mr."],
  ["السيدة", "Mrs."],
  ["سيد", "Mr."],
  ["سيدة", "Ms."],
  ["شيخ", "Shiekh"],
  ["الشيخ", "Alshiekh"],
  ["شيخة", "Shiekha"],
  ["الشيخة", "Alshiekha"],
  ["عم", "Am"],
  ["عمة", "Ama"],
  ["عمو", "Amo"],
  ["عمتو", "Amto"],
  ["كريم", "Kaream"],
  ["كريمة", "Kareama"],
]);

module.exports = { arabicPrefixesMap };
